#!/usr/bin/env bash

wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

if wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -q MUTED; then
    notify-send -u normal -t 1500 "Microphone" "Microphone Muted"
else
    notify-send -u normal -t 1500 "Microphone" "Microphone Enabled"
fi